### ISSUE TITLE
Memory leakage when storing molecule objects in an iterable

### ISSUE THREAD

**Issue by mgarort** [rdkit/rdkit#3239]
------------------------------------------------------------------------
OS: Ubuntu 18
Python version: `Python 3.6.10 :: Anaconda, Inc.`
RDKit version: 2020.03.3, from `conda-forge` (installed as indicated in the [official installation instructions](https://rdkit.org/docs/Install.html))
ipython version: 7.13.0
------------------------------------------------------------------------

Hi,

I'm opening this new issue following up from a comment in  #2556 . Both issues are memory leakages but they seem to be different.

I am experiencing a big memory leak while creating RDKit molecule objects. I'm using the function `Chem.MolFromSmiles`, although I suspect that this could happen with molecule objects in general, whereas they come from `Chem.MolFromSmiles` or have been obtained in some other way. It happens even if the SMILES strings are all parsed correctly.

The issue seems to occur when a lot of molecule objects are stored in an iterable (such as a list or a Pandas Series) and their memory stays allocated even after the iterable is deleted. Maybe I just don't understand how garbage collection works in Python and I'm doing something wrong. If this is the case please let me know.

Consider the following minimal example where memory IS NOT leaked (or maybe it is leaked, but very little). I am attaching the sample file used, which contains 10000 valid SMILES strings that are correctly parsed  ([sample_valid_smiles.txt](https://github.com/rdkit/rdkit/files/4800362/sample_valid_smiles.txt)):

``` python
import psutil
from rdkit import Chem
import pandas as pd

process= psutil.Process()
start_rss = process.memory_info().rss

df = pd.read_csv('sample_valid_smiles.txt',sep='\t')
for smiles in df['SMILES']:
    mol = Chem.MolFromSmiles(smiles)
del mol

rss = process.memory_info().rss - start_rss
print("leaks", rss/(1024**2), "mb")
```

This prints `leaks 1.84375 mb`, which is negligible. 

However, when all molecule objects are stored, there IS a significant leakage. When storing them in a list:

``` python
import psutil
from rdkit import Chem
import pandas as pd

process= psutil.Process()
start_rss = process.memory_info().rss

mol_list = []
df = pd.read_csv('sample_valid_smiles.txt',sep='\t')
for smiles in df['SMILES']:
    mol_list.append(Chem.MolFromSmiles(smiles))
del mol_list

rss = process.memory_info().rss - start_rss
print("leaks", rss/(1024**2), "mb")
```

the leakage in this case  prints as `leaks 132.03125 mb`.  

A similar result is obtained when the molecules are stored in a Pandas Series within a DataFrame. (This was my original use case: I have a DataFrame column that has SMILES strings, and let's say that I want to canonicalize them. I would first create a new column containing molecule objects with `df['mol'] = df['SMILES'].map(Chem.MolFromSmiles)`, and then I would create canonical SMILES with `df['canon_SMILES'] = df['mol'].map(Chem.MolToSmiles)`.)

``` python
import psutil
from rdkit import Chem
from functools import partial
import pandas as pd

process= psutil.Process()
start_rss = process.memory_info().rss

df = pd.read_csv('sample_valid_smiles.txt',sep='\t')
df['mol'] = df['SMILES'].map(Chem.MolFromSmiles)
df =  df.drop('mol',axis=1)

rss = process.memory_info().rss - start_rss
print("leaks", rss/(1024**2), "mb")
```

This prints `leaks 133.26953125 mb`.

I think I may be able to avoid this leakage by concatenating the input and output functions I want to use (for instance, `Chem.MolFromSmiles` and `Chem.MolToSmiles` in the canonicalization example above). However, I would like to know whether this is a bug or I'm doing something wrong in order to avoid it in the future. Right now it is a pain because I need to process ~400k molecules, and the leakage adds up and ends up freezing my laptop.

Thanks!

**Comment by adalke** [comment]
I don't see a leak. I see you creating a Chem.Mol molecule object and keeping the object around in the pandas table. The table keeps a reference to the molecule object, so it's never deallocated.

**Comment by mgarort** [comment]
Hi @adalke , thanks for your quick reply. I what you mean in my code and I've fixed it (`df.drop('mol',axis=1)` instead of `df = df.drop('mol',axis=1)`; by mistake I copied the wrong ipython cell into GitHub).

The result is the same as the one described before. In fact, as you can see in the second code block above, I obtain the same result if using the list `mol_list` instead of a DataFrame, and the excess memory allocated is still there after  `del mol_list`.

**Comment by bp-kelley** [comment]
You have to be pretty careful here as on some operating systems freeing memory doesn’t actually return it to the kernel.

Windows does, I think Linux does virtual memory paging so psutil may not display the info you expect.

----
Brian Kelley

**Comment by mgarort** [comment]
I see, I didn't know this, thanks. However, when I monitor memory usage with `htop` it definitely goes up while creating and deleting a lot of molecule objects, up to the point that my system freezes. So there seems to be a problem.

**Comment by adalke** [comment]
My apologizes actually, I overlooked the original drop.

The second code block does a "del mol_list" but it also needs a "del df" because the read_csv returns an allocated DataFrame which is still hanging around when you do the measurement.

It's very difficult for me to believe that there's an issue in RDKit or Pandas, because the interaction here is at very common, widely shared level so you would expect everyone to run across it.

bp-kelley is right - it's hard to know if what you are measuring only actively used memory space or if it also includes deallocated memory which has been marked dirty but hasn't been reclaimed.

A more definitive way to check for a leak is not to read everything up to some high amount then remove it, but to read a small amount over and over. This lets the memory manager re-use deallocated memory. Something like:
```
process= psutil.Process()
start_rss = process.memory_info().rss
for i in range(100):
  mol_list = []
  df = pd.read_csv('sample_valid_smiles.txt',sep='\t')
  for smiles in df['SMILES']:
      mol_list.append(Chem.MolFromSmiles(smiles))
  del mol_list, df
  rss = process.memory_info().rss - start_rss
  print(i, "leaks", rss/(1024**2), "mb")

**Comment by e-kwsm** [comment]
I don't know the detail of Python's memory allocation strategy, but this seems to be due to it.
https://stackoverflow.com/questions/1316767/how-can-i-explicitly-free-memory-in-python/1316788#1316788

If the code is modified, e.g, as follows
```python
max_len = 10000  # original size
mol_list = []
with open("sample_valid_smiles.txt") as f:  # no pandas
    for s in f:
        mol_list.append(Chem.MolFromSmiles(s))
        if len(mol_list) > max_len:
            mol_list = []
del mol_list
```

Then

| max_len | leak / MiB |
|---------:|-----------:|
|     1 |   0.7 |
|    10 |   1.1 |
|   100 |   2.0 |
|  1000 |  14.0 |
|  5000 |  65.9 |
| 10000 | 130.6 |

**Comment by mgarort** [comment]
Hi @adalke , thanks for the snippet. I tried  it and the result is `leaks 131.0234375 mb` 100 times in a row. However, I agree that a major issue is unlikely given that Pandas and RDKit are used together so often, that someone would have noticed before me. But at the same time I'm quite confused by what I see so I would like to at least understand it to avoid it in the future.

@e-kwsm I didn't fully understand your snippet, did you print the megabytes "leaked" within the `if len(mol_list) > max_len` statement, or after the entire loop and `del`?

**Comment by adalke** [comment]
That means there's no leak. If there were a leak, that value would increase each time through the loop.

That is, the first time through the system takes 131MB over the initial configuration. The second time through it's still at 131MB over the initial configuration, so there was no leak in the second iteration. Nor the third, etc.

What you are measuring includes a number of things: any data structures (like the data frame) that were created after the initial measurement, any Python object which was freed (at the Python level) but where the memory space was stored in a "free list" for possible fast re-use, any memory which was deallocated but which was part of a memory page containing regions which are still in use (these are often called "holes"), any memory pages which were deallocated by the C-level memory manager but which the OS didn't yet re-use -- because it doesn't take up any real space other than an small entry in the operating system's table.

The "free list", "holes", and OS-level memory manager will re-use existing unused space if possible, because it's faster.

The best way to find a leak is to repeat the same thing many times, to see if the underlying system is simply waiting to re-use memory, rather than leaking memory.

**Comment by mgarort** [comment]
I see! So I guess in my case it was a matter of memory not being deallocated and reused by the OS, rather than it leaking. Makes sense.

In that case I'm going to close this issue, and if other people are not convinced they can reply and possibly reopen.

Thanks a lot everyone!
