### ISSUE TITLE
Clashes in 2D layout with bridged systems

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#6753]
@rachelnwalker @cdvonbargen 
Following conversations we had during the 2023 RDKit UGM, here's a report of a case where the RDKit generates a layout with many clashes, while CoordGen does a better job:

```
from rdkit import Chem
from rdkit.Chem.Draw import rdDepictor

mol = Chem.MolFromSmiles("C1CC2CN(CC1N2c1ccccc1)c1cccc(c1)-c1ccccc1")
rdDepictor.SetPreferCoordGen(False)
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/0acc8237-14a5-49b2-8764-6f0ea4ae30a1)

```
rdDepictor.SetPreferCoordGen(True)
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/4c82df1c-ce97-4ea4-9c9c-15a1d2b120d5)

**Comment by rachelnwalker** [comment]
Thank you @ptosco, and sorry for the late reply! We are going to try to update RDKit's coordinate generation method to address cases like this.

**Comment by cdvonbargen** [comment]
@ZontaNicola is actually currently working on this -- would it be possible to reopen and assign to him?

**Comment by greglandrum** [comment]
@cdvonbargen @ZontaNicola I don't seem to be able to assign it to Nic, but that's fine.

**Comment by ZontaNicola** [comment]
Thanks, this should be fixed in the next update of https://github.com/rdkit/rdkit/pull/7975

**Comment by greglandrum** [comment]
@ZontaNicola this was not affected by #7975, which dealt with multi-fragment molecules.
Did you mean to reference some other PR?

**Comment by ZontaNicola** [comment]
I think what we need here is a way to have different templates for the same ring system. https://github.com/rdkit/molecular_templates/pull/12 deals with it

**Comment by greglandrum** [comment]
> I think what we need here is a way to have different templates for the same ring system. [rdkit/molecular_templates#12](https://github.com/rdkit/molecular_templates/pull/12) deals with it

@ZontaNicola Sounds good. That PR has an outstanding suggestion, then we can merge it

**Comment by greglandrum** [comment]
I can confirm that this is still present in 2025.09.3

<img width="845" height="530" alt="Image" src="https://github.com/user-attachments/assets/6fbd68d0-4bba-481d-aee9-6b94351589b6" />

**Comment by rachelnwalker** [comment]
Commenting because @ZontaNicola is doing some template work and I think this may be addressable
